package com.zzl.crm.workbench.pojo;

public class ClueRemark {
    //主键id
    private String id;
    //备注内容
    private String noteContent;
    //创建人
    private String createBy;
    //创建时间
    private String createTime;
    //修改人
    private String editBy;
    //修改时间
    private String editTime;
    //修改标志
    private String editFlag;
    //线索id
    private String clueId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue_remark.id
     *
     * @return the value of tbl_clue_remark.id
     *
     * @mbg.generated Fri May 06 22:00:22 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue_remark.id
     *
     * @param id the value for tbl_clue_remark.id
     *
     * @mbg.generated Fri May 06 22:00:22 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue_remark.note_content
     *
     * @return the value of tbl_clue_remark.note_content
     *
     * @mbg.generated Fri May 06 22:00:22 CST 2022
     */
    public String getNoteContent() {
        return noteContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue_remark.note_content
     *
     * @param noteContent the value for tbl_clue_remark.note_content
     *
     * @mbg.generated Fri May 06 22:00:22 CST 2022
     */
    public void setNoteContent(String noteContent) {
        this.noteContent = noteContent == null ? null : noteContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue_remark.create_by
     *
     * @return the value of tbl_clue_remark.create_by
     *
     * @mbg.generated Fri May 06 22:00:22 CST 2022
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue_remark.create_by
     *
     * @param createBy the value for tbl_clue_remark.create_by
     *
     * @mbg.generated Fri May 06 22:00:22 CST 2022
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue_remark.create_time
     *
     * @return the value of tbl_clue_remark.create_time
     *
     * @mbg.generated Fri May 06 22:00:22 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue_remark.create_time
     *
     * @param createTime the value for tbl_clue_remark.create_time
     *
     * @mbg.generated Fri May 06 22:00:22 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue_remark.edit_by
     *
     * @return the value of tbl_clue_remark.edit_by
     *
     * @mbg.generated Fri May 06 22:00:22 CST 2022
     */
    public String getEditBy() {
        return editBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue_remark.edit_by
     *
     * @param editBy the value for tbl_clue_remark.edit_by
     *
     * @mbg.generated Fri May 06 22:00:22 CST 2022
     */
    public void setEditBy(String editBy) {
        this.editBy = editBy == null ? null : editBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue_remark.edit_time
     *
     * @return the value of tbl_clue_remark.edit_time
     *
     * @mbg.generated Fri May 06 22:00:22 CST 2022
     */
    public String getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue_remark.edit_time
     *
     * @param editTime the value for tbl_clue_remark.edit_time
     *
     * @mbg.generated Fri May 06 22:00:22 CST 2022
     */
    public void setEditTime(String editTime) {
        this.editTime = editTime == null ? null : editTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue_remark.edit_flag
     *
     * @return the value of tbl_clue_remark.edit_flag
     *
     * @mbg.generated Fri May 06 22:00:22 CST 2022
     */
    public String getEditFlag() {
        return editFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue_remark.edit_flag
     *
     * @param editFlag the value for tbl_clue_remark.edit_flag
     *
     * @mbg.generated Fri May 06 22:00:22 CST 2022
     */
    public void setEditFlag(String editFlag) {
        this.editFlag = editFlag == null ? null : editFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue_remark.clue_id
     *
     * @return the value of tbl_clue_remark.clue_id
     *
     * @mbg.generated Fri May 06 22:00:22 CST 2022
     */
    public String getClueId() {
        return clueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue_remark.clue_id
     *
     * @param clueId the value for tbl_clue_remark.clue_id
     *
     * @mbg.generated Fri May 06 22:00:22 CST 2022
     */
    public void setClueId(String clueId) {
        this.clueId = clueId == null ? null : clueId.trim();
    }
}
