package com.zzl.crm.workbench.pojo;

public class Clue {
    //主键id
    private String id;
    //全名
    private String fullname;
    //称谓
    private String appellation;
    //所有者
    private String owner;
    //公司
    private String company;
    //职位
    private String job;
    //邮箱
    private String email;
    //公司座机
    private String phone;
    //网站
    private String website;
    //电话
    private String mphone;
    //线索状态
    private String state;
    //线索来源
    private String source;
    //创建者
    private String createBy;
    //创建时间
    private String createTime;
    //修改者
    private String editBy;
    //修改时间
    private String editTime;
    //描述
    private String description;
    //联系人摘要
    private String contactSummary;
    //下次联系时间
    private String nextContactTime;
    //详细地址
    private String address;


    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getFullname() {
        return fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.appellation
     *
     * @return the value of tbl_clue.appellation
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getAppellation() {
        return appellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.appellation
     *
     * @param appellation the value for tbl_clue.appellation
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setAppellation(String appellation) {
        this.appellation = appellation == null ? null : appellation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.owner
     *
     * @return the value of tbl_clue.owner
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.owner
     *
     * @param owner the value for tbl_clue.owner
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.company
     *
     * @return the value of tbl_clue.company
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.company
     *
     * @param company the value for tbl_clue.company
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.job
     *
     * @return the value of tbl_clue.job
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.job
     *
     * @param job the value for tbl_clue.job
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.email
     *
     * @return the value of tbl_clue.email
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.email
     *
     * @param email the value for tbl_clue.email
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.phone
     *
     * @return the value of tbl_clue.phone
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.phone
     *
     * @param phone the value for tbl_clue.phone
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.website
     *
     * @return the value of tbl_clue.website
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.website
     *
     * @param website the value for tbl_clue.website
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.mphone
     *
     * @return the value of tbl_clue.mphone
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getMphone() {
        return mphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.mphone
     *
     * @param mphone the value for tbl_clue.mphone
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setMphone(String mphone) {
        this.mphone = mphone == null ? null : mphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.state
     *
     * @return the value of tbl_clue.state
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.state
     *
     * @param state the value for tbl_clue.state
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.source
     *
     * @return the value of tbl_clue.source
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.source
     *
     * @param source the value for tbl_clue.source
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.create_by
     *
     * @return the value of tbl_clue.create_by
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.create_by
     *
     * @param createBy the value for tbl_clue.create_by
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.create_time
     *
     * @return the value of tbl_clue.create_time
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.create_time
     *
     * @param createTime the value for tbl_clue.create_time
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.edit_by
     *
     * @return the value of tbl_clue.edit_by
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getEditBy() {
        return editBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.edit_by
     *
     * @param editBy the value for tbl_clue.edit_by
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setEditBy(String editBy) {
        this.editBy = editBy == null ? null : editBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.edit_time
     *
     * @return the value of tbl_clue.edit_time
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.edit_time
     *
     * @param editTime the value for tbl_clue.edit_time
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setEditTime(String editTime) {
        this.editTime = editTime == null ? null : editTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.description
     *
     * @return the value of tbl_clue.description
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.description
     *
     * @param description the value for tbl_clue.description
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.contact_summary
     *
     * @return the value of tbl_clue.contact_summary
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getContactSummary() {
        return contactSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.contact_summary
     *
     * @param contactSummary the value for tbl_clue.contact_summary
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setContactSummary(String contactSummary) {
        this.contactSummary = contactSummary == null ? null : contactSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.next_contact_time
     *
     * @return the value of tbl_clue.next_contact_time
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getNextContactTime() {
        return nextContactTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.next_contact_time
     *
     * @param nextContactTime the value for tbl_clue.next_contact_time
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setNextContactTime(String nextContactTime) {
        this.nextContactTime = nextContactTime == null ? null : nextContactTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue.address
     *
     * @return the value of tbl_clue.address
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue.address
     *
     * @param address the value for tbl_clue.address
     *
     * @mbg.generated Thu May 05 18:16:30 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}
